### ISSUE TITLE
Milestone2_05-new plot suggestion

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/DSCI_532_L01_group101_dashboards#17]
Hi Zoe and Jake. I was reflecting on our research questions:

> 1. How has the life expectancy by country changed over time?
> 2. How are monetary factors associated with life expectancy?
> 3. Does the life expectancy between developing and developed countries differ?

I think we don't have a plot that directly answers number 2 yet.

To address this, I am suggesting we replace the histogram plot suggest for the bottom right panel with a plot that shows GDP on the X axis and Life Expectancy on the Y axis.

I will work on creating this now.

**Comment by SamEdwardes** [comment]
Created a pull request for new plot https://github.com/UBC-MDS/DSCI_532_L01_group101_dashboards/pull/19

**Comment by zoepan00** [comment]
Yeah sounds good!
