### ISSUE TITLE
General Feedback for Milestone 1

### ISSUE THREAD

**Issue by ellentkoch** [UBC-MDS/DSCI_532_L01_group101_dashboards#22]
Mechanics: Remember that the links on your github.ubc.ca account should link to specific commit versions of files. All of the necessary files in are present. Some commit messages were not very meaningful but this has improved.

Proposal: Very clearly explained motivation and purpose, and description of the data! It would be good to also include in your usage scenario an example for the 3rd question. 

Visualization: Your visualization looks attractive and the different components are clearly labelled. Your dashboard seems quite ambitious for the given time frame with all of the different interactive components, you may want to remove one of the less important features if you find you are getting pressed for time. Feel free to meet with me at OH if you find this is the case and want some suggestions. Some of the text is small and difficult to read.

Team Contract/Code of Conduct: Team Contract could be more detailed, specific, and organized in a meaningful way. For example, the bullet points under Primary sources of communication would make sense under the Communications header. There is also repetition between some of the other bullet points. Some parts need clarification – Examples: does no work on Sundays also mean no slack messages? What if someone can’t make it to a meeting? etc. The Code of Conduct looks great. 

@SamEdwardes @agdal1125 @zoepan00

**Comment by SamEdwardes** [comment]
Thank you for the feedback Ellen!
