### ISSUE TITLE
Suggested design change: move filter sidebar position

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/DSCI_532_L01_group101_dashboards#35]
Suggesting that we move sidebar filter to below the line plots as it only effects the line plots.

<img width="936" alt="Screen Shot 2019-12-03 at 9 53 24 AM" src="https://user-images.githubusercontent.com/18248949/70076051-d92a2000-15b2-11ea-98ac-20eaf95dc797.png">

**Comment by agdal1125** [comment]
Then we only need two plot columns! I will work on this.
