### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ellentkoch** [UBC-MDS/DSCI_532_L01_group101_dashboards#39]
Great work on your dashboard everyone! Here is my feedback:

**Mechanics:** Overall mechanics look great, team members are communicating through issues, using pull requests, and commit messages are informative. 

**App:** The types of visuals are well chosen for the data, and you have implemented an impressive amount of interactive elements! Everything in the app seems to be functioning as expected and the research questions are addressed. The axes labels are clear and easy to read, and the choices for different axes options are relevant. Here are a few suggestions: 
- For the line plots, there is a default showing for developing countries but not for developed countries, which is confusing when you first open up the app because the developing countries are plotted, but "developed countries" is selected. This should be fixed (High priority).
- The app description is good, but you could clarify that the values listed at the top are the mean for the entire world. You should also clarify the purpose of “GDP log” in the World Map graph.
- The user needs to use a scroll bar to see the entire graph, which is inconvenient. 
- For the “point colour” part in the scatterplot, it would be interesting to have the option to only show developed vs. undeveloped countries rather than both at the same time (lower priority).

**Reflection:** The reflection is thorough and well-written. A few minor typos/grammatical errors. 

Overall, nice work, I enjoyed exploring your app! @agdal1125 @zoepan00 @SamEdwardes

**Comment by SamEdwardes** [comment]
Thank you for the feedback Ellen! We have reviewed and summarized what we  have addressed in #44.
